version: '3.9'

services:
  web:
    build: .
    container_name: django
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - rabbitmq
    restart: on-failure

  microservice:
    container_name: fastapi
    build: ./microservices/app
    ports:
      - "8001:8001"
    env_file:
      - ./.env
  db:
    image: postgres:14.5-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    env_file:
      - ./.env
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    restart: always
    container_name: celery
    build: .
    command: sh ./entrypoint_celery.sh
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
volumes:
  postgres_data:
